services:
    imcger.imgupload.admin.controller:
        class: imcger\imgupload\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@request'
            - '@ext.manager'

    imcger.imgupload.ajax_controller:
        class: imcger\imgupload\controller\ajax_controller
        arguments:
            - '@config'
            - '@user'
            - '@request'
            - '@dbal.conn'
            - '@auth'
            - '@language'
            - '@ext.manager'
            - '@filesystem'
            - '%core.root_path%'
            - '%core.php_ext%'

    imcger.imgupload.listener:
        class: imcger\imgupload\event\main_listener
        arguments:
            - '@config'
            - '@language'
            - '@upload_imagesize'
            - '@dbal.conn'
            - '@template'
            - '@ext.manager'
            - '@controller.helper'
        tags:
            - { name: event.listener }
