services:
    imcger.imgupload.listener:
        class: imcger\imgupload\event\main_listener
        arguments:
            - '@config'
            - '@request'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }
